<?php
CONST PREFIX = "-->";
CONST INTERFIX = " - ";
CONST SUFFIX = " ";
CONST DATE_LOG = "DATE:";
CONST IP_LOG = "IP:";
CONST NUMBER_LOG = "NUMBER:";
CONST ACTION_LOG = "ACTION:";
CONST INPUT_LOG = "INPUT:";
?>
